decode option event arg
paritytech/substrate-subxt pull request #158
Opened 2020-09-03 12:43 UTC by gregdhill

Signed-off-by: Gregory Hill <gregorydhill@outlook.com>

A lot of code shift here is due to `cargo fmt`, I can revert this if needs be. The main change here is to enable `Option` decoding, required for [PolkaBTC](https://github.com/interlay/BTC-Parachain/blob/master/crates/staked-relayers/src/lib.rs#L1039).

2020-09-03 13:07 UTC, dvc94ch commented
Can you run cargo +nightly fmt and push?

2020-09-03 13:34 UTC, dvc94ch commented
Looks reasonable to me, thanks! @ascjones is the repo master

2020-09-03 15:47 UTC, ascjones requested changes
Thanks for this - but from what I can tell it might not work because the `Option` is not decoded correctly, i.e. it should first read the leading byte. If you've tested it and it works happy to be proved wrong.

2020-09-03 15:47 UTC, ascjones commented on src/metadata.rs
> +    Option(Option<Box<EventArg>>),
Why the extra `Option`? Should just be `Option(Box<EventArg>)`

2020-09-03 15:47 UTC, ascjones commented on src/events.rs
> +                EventArg::Option(arg) => {
See the encoding of `Option` here: https://github.com/paritytech/parity-scale-codec/blob/50c50b3fd7c93d9b98b65219208793d4ecb82acd/src/codec.rs#L548.

You would need to check the first byte to see whether it's `Some` or `None`, as in the decode impl: https://github.com/paritytech/parity-scale-codec/blob/50c50b3fd7c93d9b98b65219208793d4ecb82acd/src/codec.rs#L558

2020-09-03 15:47 UTC, ascjones commented on src/metadata.rs
> +                Ok(EventArg::Option(Some(Box::new(s[7..s.len() - 1].parse()?))))
The `EventArg::Option(None)` is never constructed so we can remove that extra option as I mention above

2020-09-07 09:36 UTC, gregdhill commented
Thanks for the feedback @ascjones, admittedly I had not dug deep enough into the serialization logic so I appreciate the guidance. I've updated the PR so please let me know what you think!

2020-09-07 10:22 UTC, ascjones commented on src/metadata.rs
> +                println!("event: {:?}", arg);
Please remove this `println!`

2020-09-07 10:43 UTC, ascjones approved these changes
LGTM

2020-09-07 13:58 UTC, merged